# Generated by Django 5.1.1 on 2024-10-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_taskmodel_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Task_Assign_Date',
            new_name='Task_assign_date',
        ),
    ]
