# Generated by Django 5.1.1 on 2024-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_rename_task_assign_date_taskmodel_task_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Task_assign_date',
            field=models.DateTimeField(),
        ),
    ]
